#
# Definition of all trackable objects
# Identifier corresponds to Trackable ID set in Tracking Tools
#
rigid_bodies:
    '1':
        pose: Robot_1/pose
        pose2d: Robot_1/ground_pose
        odom: Robot_1/Odom
        tf: tf
        child_frame_id: Robot_1/base_link
        parent_frame_id: world
    '2':
        pose: Robot_2/pose
        pose2d: Robot_2/ground_pose
        odom: Robot_2/Odom
        tf: tf
        child_frame_id: Robot_2/base_link
        parent_frame_id: world
    '3':
        pose: Robot_3/pose
        pose2d: Robot_3/ground_pose
        odom: Robot_3/Odom
        tf: tf
        child_frame_id: Robot_3/base_link
        parent_frame_id: world

optitrack_config:
        multicast_address: 235.255.42.99
        command_port: 1510
        data_port: 1512
        enable_optitrack: true